### ISSUE TITLE
Include raw data in createPost

### ISSUE THREAD

**Issue by spacenerdmo** [kaiwood/pnut-butter#6]
Allow for the addition of raw data in new posts allowing for things like oembeds or long posts or other raw types to be attached.

**Comment by kaiwood** [comment]
Support for adding raw options should work with 0.18.0 now, there is an example in the docs here: https://kaiwood.github.io/pnut-butter/module-posts.html#~createPost

Something like 

```javascript
const { meta} = await pnut.createPost("Awesome post with raw data", {
  raw: {
    type: "io.pnut.core.language",
    value: {
      language: "en"
    }
  }
});
```

should work. There's still work left, the other methods for creating messages and stuff need this too, but I wanted to get this first one out quickly ;)
